version: '3.8'
services:
  mongodb:
    image: mongo:latest
    ports:
    - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  server:
    build: ./server
    ports:
      - 5000:5000
    depends_on:
      - mongodb
    environment:
      - DB_URL=mongodb://mongodb:27017/fullStackApp
  client:
    build: ./client
    ports:
      - 3000:3000
    depends_on:
      - server
volumes:
  mongodb_data:
